CREATE DATABASE MILENO_DATABASE
USE MILENO_DATABASE

CREATE TABLE aluno (
	ID_ALUNO INT PRIMARY KEY,
	NOME_ALUNO VARCHAR(50) NOT NULL,
	ALUNO_ALOCADO BOOLEAN NOT NULL DEFAULT 0,
	ID_TURMA INT,
	FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID_TURMA)
);

CREATE TABLE turma (
	ID_TURMA INT PRIMARY KEY,
	CODIGO_TURMA VARCHAR (15),
	NOME_TURMA VARCHAR (30)
)
