USE MILENO_DATABASE
INSERT INTO aluno (ID_ALUNO, NOME_ALUNO, ALUNO_ALOCADO, ID_TURMA)
VALUES (1, 'Yara', TRUE, 1);
INSERT INTO aluno (ID_ALUNO, NOME_ALUNO, ALUNO_ALOCADO, ID_TURMA)
VALUES (2, 'Alessandro', TRUE, 2);