USE MILENO_DATABASE
INSERT INTO turma (ID_TURMA, CODIGO_TURMA, NOME_TURMA)
VALUES (1, '2819', 'ENGENHARIA DE DADOS');
INSERT INTO turma (ID_TURMA, CODIGO_TURMA, NOME_TURMA)
VALUES (2, '2839', 'CIÊNCIA DE DADOS');